#!/bin/bash

export nItems=$1
export nSamples=$2
export stamp=out.$nItems.$nSamples.$(date +"%Y-%m-%d-%H-%M-%S")

R CMD BATCH --no-restore --no-save --no-readline script.R $stamp.out &
tail --pid=$! -F $stamp.out

