#!/usr/bin/env Rscript

library(aibd2)

outdir <- "distribution"
dir.create(outdir,showWarnings=FALSE)
setwd(outdir)

mass <- 1.0

nItems <- 5
distIBP <- ibp(mass,nItems)
saveRDS(distIBP, paste0("ibp-",mass,".rds"))

states <- c("New Hampshire","Iowa","Wisconsin","California","Nevada")
data <- USArrests[states,]
dist <- as.matrix(dist(scale(data)))
for ( temperature in c(0,1,2,5,10) ) {
  similarity <- exp(-temperature*dist)
  distMAIBD <- aibd(mass,NULL,similarity)
  saveRDS(distMAIBD, paste0("maibd-",mass,"-",temperature,".rds"))
}

